/**
 * dsh-jenkins-panel client bundle 构建（FIN-M3-01 阶段 1 修复）
 *
 * dsh web 的 client 模块系统要求每个 bundle 的 client 半以
 * `window.__ModuleLoader__.load({ id, factory: (require) => ... })` 格式交付
 * （实测：直出 ESM 会被 client-modules 拒绝——"loaded without registering via __ModuleLoader__.load"）。
 * 配方参照同型插件 dsh-eap-todo（scripts/build-client.mjs）+ better-sidebar 产物：
 * - esbuild bundle → CJS（require 由 loader 注入，react/react-dom 子路径由宿主模块表提供）；
 * - jsx automatic（`require("react/jsx-runtime")`，better-sidebar 同款）；
 * - 类名为全局字面量（非 CSS Modules 绑定），样式经本脚本改写的 CSS 模块在运行时注入。
 *
 * CSS 交付（0.1.5 实测，关键）：**运行时 `<style>` 注入，CSS 文本以 JS 字符串嵌入 bundle**
 * （better-sidebar 产物同款、在该宿主实测可行）。两条死路，别再走：
 *  1. 源码里 `require('*.css')` / `import '*.css'` 交给模块表解析——`*.css` 不在 0.1.5 的
 *     client 模块表里，必然 miss 并抛 "missed the module table"；
 *  2. 构建期把 CSS 抽成 `lib/client.css` 旁置文件——宿主对外部插件**没有任何 CSS 加载
 *     通道**（官方插件的 CSS 是 shell 构建期内联进 `index-*.css` 的，外部插件没有这个
 *     构建期），文件写出来没人消费，症状就是「设置页/面板样式全丢」。
 * 注入用 `textContent`（不经 HTML 解析），CSS 文本里含 `</style` 也安全——该坑只在把
 * CSS 内嵌进 HTML 标记（innerHTML/服务端拼接）时存在。插件自带 `<style id>` 幂等去重，
 * 已存在则原地更新 textContent（HMR 重载后样式取最新版且不重复堆积）。
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { basename, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as esbuild from 'esbuild'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))
const id = pkg.name

/**
 * 把 *.module.css 副作用导入改写成「运行时注入 <style>」的 JS 模块。
 * 去重锚：`<style data-plugin="dsh-jenkins-panel" data-plugin-css="<tagId>">`，
 * tagId = `<包名>/<css 文件名>`，一份 CSS 恰好一个标签（幂等 + 内容更新）。
 */
function cssInjectModule(tagId, css) {
  return `/* generated by scripts/build-client.mjs from ${tagId} (runtime style injection) */
(function () {
\tif (typeof document === "undefined") return;
\tvar tag = document.querySelector('style[data-plugin-css="' + ${JSON.stringify(tagId)} + '"]');
\tif (tag === null) {
\t\ttag = document.createElement("style");
\t\ttag.dataset.plugin = ${JSON.stringify(id)};
\t\ttag.dataset.pluginCss = ${JSON.stringify(tagId)};
\t\tdocument.head.appendChild(tag);
\t}
\ttag.textContent = ${JSON.stringify(css)};
})();
`
}

const cssCollectPlugin = {
  name: 'dsh-jenkins-panel-css-collect',
  setup(build) {
    build.onLoad({ filter: /\.css$/ }, async (args) => {
      const css = await readFile(args.path, 'utf8')
      const tagId = `${id}/${basename(args.path)}`
      // CSS 变成一段自执行的注入模块：不产生 require、注入幂等（见文件头「CSS 交付」）
      return { contents: cssInjectModule(tagId, css), loader: 'js' }
    })
  },
}

const result = await esbuild.build({
  entryPoints: [resolve(root, 'src/client/index.tsx')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  jsx: 'automatic',
  write: false,
  logLevel: 'silent',
  plugins: [cssCollectPlugin],
  // 浏览器基线由宿主提供（dsh web 前端播种 React 单实例；子路径 react-dom/client、react/jsx-runtime 亦在模块表）
  external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client'],
})

const code = result.outputFiles[0].text
const wrapped = `window.__ModuleLoader__.load({
\tid: ${JSON.stringify(id)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
${code}
\t\treturn module.exports;
\t},
});
`

await mkdir(resolve(root, 'lib'), { recursive: true })
await writeFile(resolve(root, 'lib/client.js'), wrapped)
console.log('[build-client] wrote lib/client.js (' + wrapped.length + ' bytes)')
